## Import Numpy

In [1]:
import numpy as np

## Creating Array

### 1D array

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


### 2D array

In [6]:
matrix = np.array([[1, 2 ,3],
                   [4 ,5 ,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


## Shape & Dimensions

In [ ]:
# shape → (rows, columns)
# ndim → number of dimensions
# ML Rule:
# Data format = (samples, features)

print(matrix.shape) #[rows , columns]
print(matrix.ndim)

(2, 3)
2


## Special Arrays

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# This generates random numbers between 0 and 1.
np.random.rand(3,2)

array([[0.54288198, 0.0468339 ],
       [0.15518317, 0.51018328],
       [0.73263793, 0.85721212]])

In [ ]:
# Creates random integers Between 1 and 9.
np.random.randint(1 , 10 , (2 ,2))

array([[1, 3],
       [6, 9]])

## Indexing and Slicing

In [16]:
matrix = np.array([[1 , 2 , 3],
                   [4 , 5 , 6],
                   [7 , 8 , 9]])

print(matrix[0])

[1 2 3]


In [17]:
print(matrix[:,1])

[2 5 8]


In [18]:
print(matrix[2,:])

[7 8 9]


In [ ]:
print(matrix[0:2,1:3]) 
# Select rows from index 0 to 2 (but NOT including 2)

[[2 3]
 [5 6]]


## Mathematical operations

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [21]:
print(a-b)

[-3 -3 -3]


In [22]:
print(np.dot(a,b))

32


### Matrix Multiplication

In [26]:
A = np.array([[1,2,3],
             [4,5,6],
             [9,2,4]])

B = np.array([[3,5,7],
              [9,5,2],
              [1,0,4]])

print(np.matmul(A , B))

[[24 15 23]
 [63 45 62]
 [49 55 83]]


### Mean and Standard Deviation

In [27]:
data = np.array([9,8,7,6])
print(np.mean(data))

7.5


In [28]:
print(np.std(data))

1.118033988749895


### Axis
Axis = 0 → Column-wise 

Axis = 1 → Row-wise

In [29]:
matrix = np.array([[1,2,4],
                   [7,5,4]])

print(np.mean(matrix,axis=0))

[4.  3.5 4. ]


In [30]:
print(np.mean(matrix,axis=1))

[2.33333333 5.33333333]


## Practice

In [31]:
import numpy as np

In [41]:
data = np.matrix([[1,2,3],
                    [4,3,2],
                    [7,3,0],
                    [1,8,4],
                    [0,6,2]],
               )

print(data[:,1])

[[2]
 [3]
 [3]
 [8]
 [6]]


In [42]:
mean = np.mean(data,axis=0)
print(mean)

[[2.6 4.4 2.2]]


## normalization
X - mean / std

In [43]:
std = np.std(data,axis=0)
print(std)

[[2.57681975 2.24499443 1.32664992]]


In [44]:
normalization = (data - mean)/std
print(normalization)

[[-0.62092042 -1.06904497  0.60302269]
 [ 0.54330537 -0.62360956 -0.15075567]
 [ 1.70753116 -0.62360956 -1.6583124 ]
 [-0.62092042  1.60356745  1.35680105]
 [-1.00899568  0.71269665 -0.15075567]]


## Dot product

In [45]:
a = np.array([1,9,5])
b = np.array([5,4,9])

dot = np.dot(a,b)
print(dot)

86
